// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 23.1 (Build Build 991 11/28/2023)
// Created on Thu Nov 20 23:56:40 2025

cpu_register cpu_register_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.we_a(we_a_sig) ,	// input  we_a_sig
	.we_x(we_x_sig) ,	// input  we_x_sig
	.we_y(we_y_sig) ,	// input  we_y_sig
	.we_sp(we_sp_sig) ,	// input  we_sp_sig
	.we_pc(we_pc_sig) ,	// input  we_pc_sig
	.we_ps(we_ps_sig) ,	// input  we_ps_sig
	.data_in(data_in_sig) ,	// input [7:0] data_in_sig
	.pc_in(pc_in_sig) ,	// input [15:0] pc_in_sig
	.A(A_sig) ,	// output [7:0] A_sig
	.X(X_sig) ,	// output [7:0] X_sig
	.Y(Y_sig) ,	// output [7:0] Y_sig
	.SP(SP_sig) ,	// output [7:0] SP_sig
	.PC(PC_sig) ,	// output [15:0] PC_sig
	.PS(PS_sig) 	// output [7:0] PS_sig
);

