// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 23.1 (Build Build 991 11/28/2023)
// Created on Fri Nov 21 08:31:58 2025

decoder decoder_inst
(
	.opcode(opcode_sig) ,	// input [7:0] opcode_sig
	.alu_op(alu_op_sig) ,	// output [4:0] alu_op_sig
	.use_alu(use_alu_sig) ,	// output  use_alu_sig
	.mem_read(mem_read_sig) ,	// output  mem_read_sig
	.mem_write(mem_write_sig) ,	// output  mem_write_sig
	.addr_mode(addr_mode_sig) ,	// output [1:0] addr_mode_sig
	.instr_size(instr_size_sig) ,	// output [1:0] instr_size_sig
	.instr_type(instr_type_sig) 	// output [2:0] instr_type_sig
);

